/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkorderPoNoRouteImport } from './routes/workorder.$poNo'
import { Route as AppWorkordersRouteImport } from './routes/_app/workorders'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppPendingRouteImport } from './routes/_app/pending'
import { Route as AppIndentsRouteImport } from './routes/_app/indents'
import { Route as AppHistoryRouteImport } from './routes/_app/history'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppPoPoNoRouteImport } from './routes/_app/po.$poNo'
import { Route as AppIndentIndentNoRouteImport } from './routes/_app/indent.$indentNo'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkorderPoNoRoute = WorkorderPoNoRouteImport.update({
  id: '/workorder/$poNo',
  path: '/workorder/$poNo',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkordersRoute = AppWorkordersRouteImport.update({
  id: '/workorders',
  path: '/workorders',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPendingRoute = AppPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => AppRoute,
} as any)
const AppIndentsRoute = AppIndentsRouteImport.update({
  id: '/indents',
  path: '/indents',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppPoPoNoRoute = AppPoPoNoRouteImport.update({
  id: '/po/$poNo',
  path: '/po/$poNo',
  getParentRoute: () => AppRoute,
} as any)
const AppIndentIndentNoRoute = AppIndentIndentNoRouteImport.update({
  id: '/indent/$indentNo',
  path: '/indent/$indentNo',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/history': typeof AppHistoryRoute
  '/indents': typeof AppIndentsRoute
  '/pending': typeof AppPendingRoute
  '/profile': typeof AppProfileRoute
  '/workorders': typeof AppWorkordersRoute
  '/workorder/$poNo': typeof WorkorderPoNoRoute
  '/indent/$indentNo': typeof AppIndentIndentNoRoute
  '/po/$poNo': typeof AppPoPoNoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/history': typeof AppHistoryRoute
  '/indents': typeof AppIndentsRoute
  '/pending': typeof AppPendingRoute
  '/profile': typeof AppProfileRoute
  '/workorders': typeof AppWorkordersRoute
  '/workorder/$poNo': typeof WorkorderPoNoRoute
  '/indent/$indentNo': typeof AppIndentIndentNoRoute
  '/po/$poNo': typeof AppPoPoNoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/indents': typeof AppIndentsRoute
  '/_app/pending': typeof AppPendingRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/workorders': typeof AppWorkordersRoute
  '/workorder/$poNo': typeof WorkorderPoNoRoute
  '/_app/indent/$indentNo': typeof AppIndentIndentNoRoute
  '/_app/po/$poNo': typeof AppPoPoNoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/history'
    | '/indents'
    | '/pending'
    | '/profile'
    | '/workorders'
    | '/workorder/$poNo'
    | '/indent/$indentNo'
    | '/po/$poNo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/history'
    | '/indents'
    | '/pending'
    | '/profile'
    | '/workorders'
    | '/workorder/$poNo'
    | '/indent/$indentNo'
    | '/po/$poNo'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/dashboard'
    | '/_app/history'
    | '/_app/indents'
    | '/_app/pending'
    | '/_app/profile'
    | '/_app/workorders'
    | '/workorder/$poNo'
    | '/_app/indent/$indentNo'
    | '/_app/po/$poNo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  WorkorderPoNoRoute: typeof WorkorderPoNoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workorder/$poNo': {
      id: '/workorder/$poNo'
      path: '/workorder/$poNo'
      fullPath: '/workorder/$poNo'
      preLoaderRoute: typeof WorkorderPoNoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workorders': {
      id: '/_app/workorders'
      path: '/workorders'
      fullPath: '/workorders'
      preLoaderRoute: typeof AppWorkordersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pending': {
      id: '/_app/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof AppPendingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/indents': {
      id: '/_app/indents'
      path: '/indents'
      fullPath: '/indents'
      preLoaderRoute: typeof AppIndentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/po/$poNo': {
      id: '/_app/po/$poNo'
      path: '/po/$poNo'
      fullPath: '/po/$poNo'
      preLoaderRoute: typeof AppPoPoNoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/indent/$indentNo': {
      id: '/_app/indent/$indentNo'
      path: '/indent/$indentNo'
      fullPath: '/indent/$indentNo'
      preLoaderRoute: typeof AppIndentIndentNoRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppIndentsRoute: typeof AppIndentsRoute
  AppPendingRoute: typeof AppPendingRoute
  AppProfileRoute: typeof AppProfileRoute
  AppWorkordersRoute: typeof AppWorkordersRoute
  AppIndentIndentNoRoute: typeof AppIndentIndentNoRoute
  AppPoPoNoRoute: typeof AppPoPoNoRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppIndentsRoute: AppIndentsRoute,
  AppPendingRoute: AppPendingRoute,
  AppProfileRoute: AppProfileRoute,
  AppWorkordersRoute: AppWorkordersRoute,
  AppIndentIndentNoRoute: AppIndentIndentNoRoute,
  AppPoPoNoRoute: AppPoPoNoRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  WorkorderPoNoRoute: WorkorderPoNoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
