/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWorkordersRouteImport } from './routes/_app/workorders'
import { Route as AppSalesDashboardRouteImport } from './routes/_app/sales-dashboard'
import { Route as AppReconciliationRouteImport } from './routes/_app/reconciliation'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppPendingRouteImport } from './routes/_app/pending'
import { Route as AppPaymentsRouteImport } from './routes/_app/payments'
import { Route as AppLedgersRouteImport } from './routes/_app/ledgers'
import { Route as AppLedgerSummaryRouteImport } from './routes/_app/ledger-summary'
import { Route as AppIndentsRouteImport } from './routes/_app/indents'
import { Route as AppHistoryRouteImport } from './routes/_app/history'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppBomRouteImport } from './routes/_app/bom'
import { Route as AppBomIndexRouteImport } from './routes/_app/bom.index'
import { Route as AppWorkorderPoNoRouteImport } from './routes/_app/workorder.$poNo'
import { Route as AppPoPoNoRouteImport } from './routes/_app/po.$poNo'
import { Route as AppPlanningTimelineRouteImport } from './routes/_app/planning/timeline'
import { Route as AppPlanningLoomRouteImport } from './routes/_app/planning/loom'
import { Route as AppPlanningFibcRouteImport } from './routes/_app/planning/fibc'
import { Route as AppPaymentPaymentNoRouteImport } from './routes/_app/payment.$paymentNo'
import { Route as AppIndentIndentNoRouteImport } from './routes/_app/indent.$indentNo'
import { Route as AppBomCustomersRouteImport } from './routes/_app/bom.customers'
import { Route as AppBomSplatRouteImport } from './routes/_app/bom.$'
import { Route as AppPlanningTimelineIndexRouteImport } from './routes/_app/planning/timeline.index'
import { Route as AppPlanningLoomIndexRouteImport } from './routes/_app/planning/loom.index'
import { Route as AppPlanningFibcIndexRouteImport } from './routes/_app/planning/fibc.index'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkordersRoute = AppWorkordersRouteImport.update({
  id: '/workorders',
  path: '/workorders',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesDashboardRoute = AppSalesDashboardRouteImport.update({
  id: '/sales-dashboard',
  path: '/sales-dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppReconciliationRoute = AppReconciliationRouteImport.update({
  id: '/reconciliation',
  path: '/reconciliation',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPendingRoute = AppPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppLedgersRoute = AppLedgersRouteImport.update({
  id: '/ledgers',
  path: '/ledgers',
  getParentRoute: () => AppRoute,
} as any)
const AppLedgerSummaryRoute = AppLedgerSummaryRouteImport.update({
  id: '/ledger-summary',
  path: '/ledger-summary',
  getParentRoute: () => AppRoute,
} as any)
const AppIndentsRoute = AppIndentsRouteImport.update({
  id: '/indents',
  path: '/indents',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBomRoute = AppBomRouteImport.update({
  id: '/bom',
  path: '/bom',
  getParentRoute: () => AppRoute,
} as any)
const AppBomIndexRoute = AppBomIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppBomRoute,
} as any)
const AppWorkorderPoNoRoute = AppWorkorderPoNoRouteImport.update({
  id: '/workorder/$poNo',
  path: '/workorder/$poNo',
  getParentRoute: () => AppRoute,
} as any)
const AppPoPoNoRoute = AppPoPoNoRouteImport.update({
  id: '/po/$poNo',
  path: '/po/$poNo',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanningTimelineRoute = AppPlanningTimelineRouteImport.update({
  id: '/planning/timeline',
  path: '/planning/timeline',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanningLoomRoute = AppPlanningLoomRouteImport.update({
  id: '/planning/loom',
  path: '/planning/loom',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanningFibcRoute = AppPlanningFibcRouteImport.update({
  id: '/planning/fibc',
  path: '/planning/fibc',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentPaymentNoRoute = AppPaymentPaymentNoRouteImport.update({
  id: '/payment/$paymentNo',
  path: '/payment/$paymentNo',
  getParentRoute: () => AppRoute,
} as any)
const AppIndentIndentNoRoute = AppIndentIndentNoRouteImport.update({
  id: '/indent/$indentNo',
  path: '/indent/$indentNo',
  getParentRoute: () => AppRoute,
} as any)
const AppBomCustomersRoute = AppBomCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppBomRoute,
} as any)
const AppBomSplatRoute = AppBomSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppBomRoute,
} as any)
const AppPlanningTimelineIndexRoute =
  AppPlanningTimelineIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppPlanningTimelineRoute,
  } as any)
const AppPlanningLoomIndexRoute = AppPlanningLoomIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPlanningLoomRoute,
} as any)
const AppPlanningFibcIndexRoute = AppPlanningFibcIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPlanningFibcRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bom': typeof AppBomRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/history': typeof AppHistoryRoute
  '/indents': typeof AppIndentsRoute
  '/ledger-summary': typeof AppLedgerSummaryRoute
  '/ledgers': typeof AppLedgersRoute
  '/payments': typeof AppPaymentsRoute
  '/pending': typeof AppPendingRoute
  '/profile': typeof AppProfileRoute
  '/reconciliation': typeof AppReconciliationRoute
  '/sales-dashboard': typeof AppSalesDashboardRoute
  '/workorders': typeof AppWorkordersRoute
  '/bom/$': typeof AppBomSplatRoute
  '/bom/customers': typeof AppBomCustomersRoute
  '/indent/$indentNo': typeof AppIndentIndentNoRoute
  '/payment/$paymentNo': typeof AppPaymentPaymentNoRoute
  '/planning/fibc': typeof AppPlanningFibcRouteWithChildren
  '/planning/loom': typeof AppPlanningLoomRouteWithChildren
  '/planning/timeline': typeof AppPlanningTimelineRouteWithChildren
  '/po/$poNo': typeof AppPoPoNoRoute
  '/workorder/$poNo': typeof AppWorkorderPoNoRoute
  '/bom/': typeof AppBomIndexRoute
  '/planning/fibc/': typeof AppPlanningFibcIndexRoute
  '/planning/loom/': typeof AppPlanningLoomIndexRoute
  '/planning/timeline/': typeof AppPlanningTimelineIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/history': typeof AppHistoryRoute
  '/indents': typeof AppIndentsRoute
  '/ledger-summary': typeof AppLedgerSummaryRoute
  '/ledgers': typeof AppLedgersRoute
  '/payments': typeof AppPaymentsRoute
  '/pending': typeof AppPendingRoute
  '/profile': typeof AppProfileRoute
  '/reconciliation': typeof AppReconciliationRoute
  '/sales-dashboard': typeof AppSalesDashboardRoute
  '/workorders': typeof AppWorkordersRoute
  '/bom/$': typeof AppBomSplatRoute
  '/bom/customers': typeof AppBomCustomersRoute
  '/indent/$indentNo': typeof AppIndentIndentNoRoute
  '/payment/$paymentNo': typeof AppPaymentPaymentNoRoute
  '/po/$poNo': typeof AppPoPoNoRoute
  '/workorder/$poNo': typeof AppWorkorderPoNoRoute
  '/bom': typeof AppBomIndexRoute
  '/planning/fibc': typeof AppPlanningFibcIndexRoute
  '/planning/loom': typeof AppPlanningLoomIndexRoute
  '/planning/timeline': typeof AppPlanningTimelineIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/bom': typeof AppBomRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/indents': typeof AppIndentsRoute
  '/_app/ledger-summary': typeof AppLedgerSummaryRoute
  '/_app/ledgers': typeof AppLedgersRoute
  '/_app/payments': typeof AppPaymentsRoute
  '/_app/pending': typeof AppPendingRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/reconciliation': typeof AppReconciliationRoute
  '/_app/sales-dashboard': typeof AppSalesDashboardRoute
  '/_app/workorders': typeof AppWorkordersRoute
  '/_app/bom/$': typeof AppBomSplatRoute
  '/_app/bom/customers': typeof AppBomCustomersRoute
  '/_app/indent/$indentNo': typeof AppIndentIndentNoRoute
  '/_app/payment/$paymentNo': typeof AppPaymentPaymentNoRoute
  '/_app/planning/fibc': typeof AppPlanningFibcRouteWithChildren
  '/_app/planning/loom': typeof AppPlanningLoomRouteWithChildren
  '/_app/planning/timeline': typeof AppPlanningTimelineRouteWithChildren
  '/_app/po/$poNo': typeof AppPoPoNoRoute
  '/_app/workorder/$poNo': typeof AppWorkorderPoNoRoute
  '/_app/bom/': typeof AppBomIndexRoute
  '/_app/planning/fibc/': typeof AppPlanningFibcIndexRoute
  '/_app/planning/loom/': typeof AppPlanningLoomIndexRoute
  '/_app/planning/timeline/': typeof AppPlanningTimelineIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bom'
    | '/dashboard'
    | '/history'
    | '/indents'
    | '/ledger-summary'
    | '/ledgers'
    | '/payments'
    | '/pending'
    | '/profile'
    | '/reconciliation'
    | '/sales-dashboard'
    | '/workorders'
    | '/bom/$'
    | '/bom/customers'
    | '/indent/$indentNo'
    | '/payment/$paymentNo'
    | '/planning/fibc'
    | '/planning/loom'
    | '/planning/timeline'
    | '/po/$poNo'
    | '/workorder/$poNo'
    | '/bom/'
    | '/planning/fibc/'
    | '/planning/loom/'
    | '/planning/timeline/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/history'
    | '/indents'
    | '/ledger-summary'
    | '/ledgers'
    | '/payments'
    | '/pending'
    | '/profile'
    | '/reconciliation'
    | '/sales-dashboard'
    | '/workorders'
    | '/bom/$'
    | '/bom/customers'
    | '/indent/$indentNo'
    | '/payment/$paymentNo'
    | '/po/$poNo'
    | '/workorder/$poNo'
    | '/bom'
    | '/planning/fibc'
    | '/planning/loom'
    | '/planning/timeline'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/bom'
    | '/_app/dashboard'
    | '/_app/history'
    | '/_app/indents'
    | '/_app/ledger-summary'
    | '/_app/ledgers'
    | '/_app/payments'
    | '/_app/pending'
    | '/_app/profile'
    | '/_app/reconciliation'
    | '/_app/sales-dashboard'
    | '/_app/workorders'
    | '/_app/bom/$'
    | '/_app/bom/customers'
    | '/_app/indent/$indentNo'
    | '/_app/payment/$paymentNo'
    | '/_app/planning/fibc'
    | '/_app/planning/loom'
    | '/_app/planning/timeline'
    | '/_app/po/$poNo'
    | '/_app/workorder/$poNo'
    | '/_app/bom/'
    | '/_app/planning/fibc/'
    | '/_app/planning/loom/'
    | '/_app/planning/timeline/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workorders': {
      id: '/_app/workorders'
      path: '/workorders'
      fullPath: '/workorders'
      preLoaderRoute: typeof AppWorkordersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales-dashboard': {
      id: '/_app/sales-dashboard'
      path: '/sales-dashboard'
      fullPath: '/sales-dashboard'
      preLoaderRoute: typeof AppSalesDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reconciliation': {
      id: '/_app/reconciliation'
      path: '/reconciliation'
      fullPath: '/reconciliation'
      preLoaderRoute: typeof AppReconciliationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pending': {
      id: '/_app/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof AppPendingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payments': {
      id: '/_app/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ledgers': {
      id: '/_app/ledgers'
      path: '/ledgers'
      fullPath: '/ledgers'
      preLoaderRoute: typeof AppLedgersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ledger-summary': {
      id: '/_app/ledger-summary'
      path: '/ledger-summary'
      fullPath: '/ledger-summary'
      preLoaderRoute: typeof AppLedgerSummaryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/indents': {
      id: '/_app/indents'
      path: '/indents'
      fullPath: '/indents'
      preLoaderRoute: typeof AppIndentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bom': {
      id: '/_app/bom'
      path: '/bom'
      fullPath: '/bom'
      preLoaderRoute: typeof AppBomRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bom/': {
      id: '/_app/bom/'
      path: '/'
      fullPath: '/bom/'
      preLoaderRoute: typeof AppBomIndexRouteImport
      parentRoute: typeof AppBomRoute
    }
    '/_app/workorder/$poNo': {
      id: '/_app/workorder/$poNo'
      path: '/workorder/$poNo'
      fullPath: '/workorder/$poNo'
      preLoaderRoute: typeof AppWorkorderPoNoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/po/$poNo': {
      id: '/_app/po/$poNo'
      path: '/po/$poNo'
      fullPath: '/po/$poNo'
      preLoaderRoute: typeof AppPoPoNoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/planning/timeline': {
      id: '/_app/planning/timeline'
      path: '/planning/timeline'
      fullPath: '/planning/timeline'
      preLoaderRoute: typeof AppPlanningTimelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/planning/loom': {
      id: '/_app/planning/loom'
      path: '/planning/loom'
      fullPath: '/planning/loom'
      preLoaderRoute: typeof AppPlanningLoomRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/planning/fibc': {
      id: '/_app/planning/fibc'
      path: '/planning/fibc'
      fullPath: '/planning/fibc'
      preLoaderRoute: typeof AppPlanningFibcRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payment/$paymentNo': {
      id: '/_app/payment/$paymentNo'
      path: '/payment/$paymentNo'
      fullPath: '/payment/$paymentNo'
      preLoaderRoute: typeof AppPaymentPaymentNoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/indent/$indentNo': {
      id: '/_app/indent/$indentNo'
      path: '/indent/$indentNo'
      fullPath: '/indent/$indentNo'
      preLoaderRoute: typeof AppIndentIndentNoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bom/customers': {
      id: '/_app/bom/customers'
      path: '/customers'
      fullPath: '/bom/customers'
      preLoaderRoute: typeof AppBomCustomersRouteImport
      parentRoute: typeof AppBomRoute
    }
    '/_app/bom/$': {
      id: '/_app/bom/$'
      path: '/$'
      fullPath: '/bom/$'
      preLoaderRoute: typeof AppBomSplatRouteImport
      parentRoute: typeof AppBomRoute
    }
    '/_app/planning/timeline/': {
      id: '/_app/planning/timeline/'
      path: '/'
      fullPath: '/planning/timeline/'
      preLoaderRoute: typeof AppPlanningTimelineIndexRouteImport
      parentRoute: typeof AppPlanningTimelineRoute
    }
    '/_app/planning/loom/': {
      id: '/_app/planning/loom/'
      path: '/'
      fullPath: '/planning/loom/'
      preLoaderRoute: typeof AppPlanningLoomIndexRouteImport
      parentRoute: typeof AppPlanningLoomRoute
    }
    '/_app/planning/fibc/': {
      id: '/_app/planning/fibc/'
      path: '/'
      fullPath: '/planning/fibc/'
      preLoaderRoute: typeof AppPlanningFibcIndexRouteImport
      parentRoute: typeof AppPlanningFibcRoute
    }
  }
}

interface AppBomRouteChildren {
  AppBomSplatRoute: typeof AppBomSplatRoute
  AppBomCustomersRoute: typeof AppBomCustomersRoute
  AppBomIndexRoute: typeof AppBomIndexRoute
}

const AppBomRouteChildren: AppBomRouteChildren = {
  AppBomSplatRoute: AppBomSplatRoute,
  AppBomCustomersRoute: AppBomCustomersRoute,
  AppBomIndexRoute: AppBomIndexRoute,
}

const AppBomRouteWithChildren =
  AppBomRoute._addFileChildren(AppBomRouteChildren)

interface AppPlanningFibcRouteChildren {
  AppPlanningFibcIndexRoute: typeof AppPlanningFibcIndexRoute
}

const AppPlanningFibcRouteChildren: AppPlanningFibcRouteChildren = {
  AppPlanningFibcIndexRoute: AppPlanningFibcIndexRoute,
}

const AppPlanningFibcRouteWithChildren = AppPlanningFibcRoute._addFileChildren(
  AppPlanningFibcRouteChildren,
)

interface AppPlanningLoomRouteChildren {
  AppPlanningLoomIndexRoute: typeof AppPlanningLoomIndexRoute
}

const AppPlanningLoomRouteChildren: AppPlanningLoomRouteChildren = {
  AppPlanningLoomIndexRoute: AppPlanningLoomIndexRoute,
}

const AppPlanningLoomRouteWithChildren = AppPlanningLoomRoute._addFileChildren(
  AppPlanningLoomRouteChildren,
)

interface AppPlanningTimelineRouteChildren {
  AppPlanningTimelineIndexRoute: typeof AppPlanningTimelineIndexRoute
}

const AppPlanningTimelineRouteChildren: AppPlanningTimelineRouteChildren = {
  AppPlanningTimelineIndexRoute: AppPlanningTimelineIndexRoute,
}

const AppPlanningTimelineRouteWithChildren =
  AppPlanningTimelineRoute._addFileChildren(AppPlanningTimelineRouteChildren)

interface AppRouteChildren {
  AppBomRoute: typeof AppBomRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppIndentsRoute: typeof AppIndentsRoute
  AppLedgerSummaryRoute: typeof AppLedgerSummaryRoute
  AppLedgersRoute: typeof AppLedgersRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppPendingRoute: typeof AppPendingRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReconciliationRoute: typeof AppReconciliationRoute
  AppSalesDashboardRoute: typeof AppSalesDashboardRoute
  AppWorkordersRoute: typeof AppWorkordersRoute
  AppIndentIndentNoRoute: typeof AppIndentIndentNoRoute
  AppPaymentPaymentNoRoute: typeof AppPaymentPaymentNoRoute
  AppPlanningFibcRoute: typeof AppPlanningFibcRouteWithChildren
  AppPlanningLoomRoute: typeof AppPlanningLoomRouteWithChildren
  AppPlanningTimelineRoute: typeof AppPlanningTimelineRouteWithChildren
  AppPoPoNoRoute: typeof AppPoPoNoRoute
  AppWorkorderPoNoRoute: typeof AppWorkorderPoNoRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBomRoute: AppBomRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppIndentsRoute: AppIndentsRoute,
  AppLedgerSummaryRoute: AppLedgerSummaryRoute,
  AppLedgersRoute: AppLedgersRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppPendingRoute: AppPendingRoute,
  AppProfileRoute: AppProfileRoute,
  AppReconciliationRoute: AppReconciliationRoute,
  AppSalesDashboardRoute: AppSalesDashboardRoute,
  AppWorkordersRoute: AppWorkordersRoute,
  AppIndentIndentNoRoute: AppIndentIndentNoRoute,
  AppPaymentPaymentNoRoute: AppPaymentPaymentNoRoute,
  AppPlanningFibcRoute: AppPlanningFibcRouteWithChildren,
  AppPlanningLoomRoute: AppPlanningLoomRouteWithChildren,
  AppPlanningTimelineRoute: AppPlanningTimelineRouteWithChildren,
  AppPoPoNoRoute: AppPoPoNoRoute,
  AppWorkorderPoNoRoute: AppWorkorderPoNoRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
